<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerTfmsh5b\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerTfmsh5b/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerTfmsh5b.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerTfmsh5b\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerTfmsh5b\appProdProjectContainer([
    'container.build_hash' => 'Tfmsh5b',
    'container.build_id' => '252e96bb',
    'container.build_time' => 1625764031,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerTfmsh5b');
